src/CrossingBorders/XBundle/Entity/RecordType.php
<?php
namespace CrossingBorders\XBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Entity
 */
class RecordType extends Base {
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @ORM\Column(type="string", unique=true, nullable=false)
     */
    protected $name;
    /**
     * @ORM\OneToMany(targetEntity="CrossingBorders\XBundle\Entity\RecordTypeField", mappedBy="recordType", cascade={"persist","remove"})
     * @ORM\OrderBy({"displayOrder" = "ASC"})
     */
    protected $recordTypeFields;
    /**
     * @ORM\OneToMany(targetEntity="CrossingBorders\XBundle\Entity\Record", mappedBy="recordType", cascade={"remove"})
     */
    protected $records;
    /**
     * @ORM\OneToMany(targetEntity="CrossingBorders\XBundle\Entity\TableColumn", mappedBy="recordType", cascade={"persist"})
     */
    private $tableColumns;
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->recordTypeFields = new \Doctrine\Common\Collections\ArrayCollection();
        $this->records = new \Doctrine\Common\Collections\ArrayCollection();
        $this->tableColumns = new \Doctrine\Common\Collections\ArrayCollection();
    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function setId($id) {
        $this->id = $id;
        return $this;
    }
    /**
     * Set name
     *
     * @param string $name
     * @return RecordType
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }
    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * Add fieldTypes
     *
     * @param \CrossingBorders\XBundle\Entity\RecordTypeField $fieldTypes
     * @return RecordType
     */
    public function addRecordTypeField(\CrossingBorders\XBundle\Entity\RecordTypeField $recordTypeFields)
    {
        $recordTypeFields->setRecordType($this);
        $this->recordTypeFields[] = $recordTypeFields;
        return $this;
    }

    /**
     * Remove fieldTypes
     *
     * @param \CrossingBorders\XBundle\Entity\RecordTypeField $fieldTypes
     */
    public function removeRecordTypeField(\CrossingBorders\XBundle\Entity\RecordTypeField $recordTypeFields)
    {
        $this->recordTypeFields->removeElement($recordTypeFields);
    }
    /**
     * Get fieldTypes
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getRecordTypeFields()
    {
        return $this->recordTypeFields;
    }
    /**
     * Clear fieldTypes
     */
    public function clearRecordTypeFields()
    {
        $this->recordTypeFields = new \Doctrine\Common\Collections\ArrayCollection();
    }
    /**
     * Add records
     *
     * @param \CrossingBorders\XBundle\Entity\Record $records
     * @return RecordType
     */
    public function addRecord(\CrossingBorders\XBundle\Entity\Record $records)
    {
        $this->records[] = $records;

        return $this;
    }
    /**
     * Remove records
     *
     * @param \CrossingBorders\XBundle\Entity\Record $records
     */
    public function removeRecord(\CrossingBorders\XBundle\Entity\Record $records)
    {
        $this->records->removeElement($records);
    }
    /**
     * Get records
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getRecords()
    {
        return $this->records;
    }
    
    /**
     * Add tableColumns
     *
     * @param \CrossingBorders\XBundle\Entity\TableColumn $tableColumns
     * @return RecordType
     */
    public function addTableColumn(\CrossingBorders\XBundle\Entity\TableColumn $tableColumns)
    {
        $tableColumns->setRecordTypeField($this);
        $this->tableColumns[] = $tableColumns;
        return $this;
    }

    /**
     * Remove tableColumns
     *
     * @param \CrossingBorders\XBundle\Entity\TableColumn $tableColumns
     */
    public function removeTableColumn(\CrossingBorders\XBundle\Entity\TableColumn $tableColumns)
    {
        $this->tableColumns->removeElement($tableColumns);
    }

    /**
     * Get tableColumns
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTableColumns()
    {
        return $this->tableColumns;
    }
    
    
    public function __toString() {
        return $this->name;
    }
}

src/CrossingBorders/XBundle/Entity/StoredFile.php
<?php
namespace CrossingBorders\XBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class StoredFile {
    //Source: http://en.wikipedia.org/wiki/Internet_media_type#Type_image
    public static $imageMimeTypes = array('image/gif',
                                          'image/jpeg',
                                          'image/pjpeg',
                                          'image/png',
                                          'image/tiff',
                                          'image/example');
    public static $videoMimeTypes = array('application/ogg',
                                          'video/avi',
                                          'video/example',
                                          'video/mpeg',
                                          'video/mp4',
                                          'video/ogg',
                                          'video/quicktime',
                                          'video/webm',
                                          'video/x-matroska',
                                          'video/x-ms-wmv',
                                          'video/x-flv');
    public static $audioMimeTypes = array('audio/basic',
                                          'audio/L24',
                                          'audio/mp4',
                                          'audio/mpeg',
                                          'audio/ogg',
                                          'audio/opus',
                                          'audio/vorbis',
                                          'audio/vorbis',
                                          'audio/vnd.rn-realaudio',
                                          'audio/vnd.wave',
                                          'audio/webm',
                                          'audio/example');
    
    protected static $thumbnailSuffix = '.thumbnail.jpeg';
    protected static $thumbnailWidth = 200;
    protected static $thumbnailHeight = 150;
    protected static $thumbnailJpegCompression = 60;
    
    protected static $defaultImageSuffix = '.default.jpeg';
    protected static $defaultImageWidth = 1600;
    protected static $defaultImageHeight = 1200;
    protected static $defaultImageJpegCompression = 80;
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $path;
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $originalName;
    private $file;
    private $temp;
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }
    /**
     * Set value
     *
     * @param File $value
     * @return FieldValueString
     */
    public function setValue($value) {
        $this->setFile($value);
        return $this;
    }
    /**
     * Get value
     *
     * @return File 
     */
    public function getValue() {
        return $this->getFile();
    }
    /**
     * Set path
     *
     * @param string $path
     * @return FieldValueString
     */
    public function setPath($path) {
        $this->path = $path;
        return $this;
    }
    /**
     * Get path
     *
     * @return string 
     */
    public function getPath() {
        //If the path is not set try to return an old path so that a still not deleted file may be used instead!
        if(is_null($this->path)) {
            return $this->temp;
        } else {
            return $this->path;
        }
    }
    /**
     * Set originalName
     *
     * @param string $orignalName
     * @return FieldValueString
     */
    public function setOriginalName($orignalName) {
        $this->originalName = $orignalName;
        return $this;
    }
    /**
     * Get originalName
     *
     * @return string 
     */
    public function getOriginalName() {
        return $this->originalName;
    }
    /**
     * Sets file.
     *
     * @param File $file
     */
    public function setFile($file = null) {
        if($file instanceof File) {
            $this->file = $file;
            // check if we have an old image path
            if (isset($this->path)) {
                // store the old name to delete after the update
                $this->temp = $this->path;
                $this->path = null;
            } else {
                $this->path = 'initial';
            }
        } else if(is_string($file) && $file == 'delete') {
            $this->removeUpload();
        }
        return $this;
    }
    /**
     * Get file.
     *
     * @return File
     */
    public function getFile() {
        if($this->file === null) {
            return new File($this->getAbsolutePath(), true);
        } else {
            return $this->file;
        }
    }
    //Get Multiple Types of Path Methods
    public function getAbsolutePath() {
        return is_null($this->getPath())
            ? null
            : self::getUploadRootDir().'/'.$this->getPath();
    }
    public function getWebPath() {
        return is_null($this->getPath())
            ? null
            : $this->getUploadDir().'/'.$this->getPath().StoredFile::$defaultImageSuffix;
    }
    public function getWebPathOriginal() {
        return is_null($this->getPath())
            ? null
            : $this->getUploadDir().'/'.$this->getPath();
    }
    public function getWebPathThumbnail() {
        return is_null($this->getPath())
            ? null
            : $this->getUploadDir().'/'.$this->getPath().StoredFile::$thumbnailSuffix;
    }
    public static function getUploadRootDir() {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.self::getUploadDir();
    }
    public static function getUploadDir() {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads';
    }
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        $file = $this->getFile();
        if (null !== $file && $file instanceof UploadedFile) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename.'.'.$this->getFile()->guessExtension();
            $this->originalName = $this->getFile()->getClientOriginalName();
        } else {
            $this->path = $this->getFile()->getFilename();
            $this->originalName = $this->getFile()->getFilename();
        }
    }
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (null === $this->getFile()) {
            return;
        }
        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move(self::getUploadRootDir(), $this->path);
        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            if(file_exists(self::getUploadRootDir().'/'.$this->temp)){
                //unlink($this->getUploadRootDir().'/'.$this->temp);
                array_map('unlink', glob(self::getUploadRootDir().'/'.$this->temp.'*'));
            }
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
        $this->generateThumbnail();
        $this->generateDefaultImage();
    }
    /**
     * @ORM\PreRemove()
     */
    public function saveFilenameForRemoval() {
        $this->temp = $this->getAbsolutePath();
    }
    /**
     * @ORM\PostRemove()
     */
    public function removeFile() {
        $file = $this->temp;
        if ($file) {
            array_map('unlink', glob($file.'*'));
        }
    }
    public function getExists() {
        try {
            $filePath = $this->getAbsolutePath();
            new File($filePath);
            return true;
        } catch(FileNotFoundException $e) {
            return false;
        }
    }
    public function getIsImage() {
        try {
            $file = new File($this->getAbsolutePath());
            return in_array($file->getMimeType(), self::$imageMimeTypes);
        } catch(FileNotFoundException $e) {
            return false;
        }
    }
    public function getIsAudio() {
        try {
            $file = new File($this->getAbsolutePath());
            return in_array($file->getMimeType(), self::$audioMimeTypes);
        } catch(FileNotFoundException $e) {
            return false;
        }
    }
    public function getIsVideo() {
        try {
            $file = new File($this->getAbsolutePath());
            return in_array($file->getMimeType(), self::$videoMimeTypes);
        } catch(FileNotFoundException $e) {
            return false;
        }
    }
    private function generateThumbnail() {
        if($this->getIsImage()) {
            $thumbImage = new \Imagick($this->getAbsolutePath());
            //Set compression
            $thumbImage->setImageCompression(\Imagick::COMPRESSION_JPEG);
            $thumbImage->setImageCompressionQuality(StoredFile::$thumbnailJpegCompression);
            //Strip out unneeded meta data
            $thumbImage->stripImage();

src/CrossingBorders/XBundle/Resources/views/Record/edit.html.twig
{% extends '::base.html.twig' %}
{% form_theme edit_form 'CrossingBordersXBundle:Form:record_fields.html.twig' %}
{% block javascripts %}
    {{ parent() }}
    {% javascripts '@CrossingBordersXBundle/Resources/public/js/record/*' %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        Record.strings.addRow = "{% trans %}Add Row{% endtrans %}";
    </script>
{% endblock %}
{% block body -%}
<h1>{% trans %}Edit{% endtrans %}</h1>    
{{ form_start(edit_form) }}
    {% if not edit_form.vars.valid %}
        <p class="text-danger">This record contains errors. Please review them below.</p>
    {% endif %}
    {% for field in edit_form %}
        {% if edit_form.submit == field %}
            {{ form_widget(field, {'attr': {'class': 'btn btn-primary'}}) }}
        {% else %}
            {{ form_row(field) }}
        {% endif %}
    {% endfor %}
{{ form_end(edit_form) }}
<ul class="record_actions list-unstyled">
    <li>{{ form_delete(delete_form) }}</li>
    <li><a href="{{ path('record') }}" class="btn btn-default">Back to the list</a></li>
</ul>
{% endblock %}

src/CrossingBorders/XBundle/Resources/views/Record/index.html.twig
{% extends '::base.html.twig' %}
{% block javascripts %}
    {{ parent() }}
    {% javascripts '@CrossingBordersXBundle/Resources/public/js/favorite/add.js' %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        Favorites.saveRoute = '{{ path('favorite_add') }}';
        Favorites.savePrompt = '{% trans %}Please enter a unique favorite name{% endtrans %}';
        Favorites.csrfToken = '{{ csrf_token('add-favorite') }}';
    </script>
{% endblock %}
{% block body -%}
    <h1>{% trans %}Records{% endtrans %}
        {% if app.user %}
            <button type="button" class="save-search btn btn-primary">
                <span class="glyphicon glyphicon-star"></span>
            </button>
        {% endif %}
        <button type="button" class="print-page btn btn-primary">
            <span class="glyphicon glyphicon-print"></span>
        </button>
        <button type="button" class="export-page-to-pdf btn btn-primary">
            <span class="fa fa-file-pdf-o"></span>
        </button>
    </h1>
    <div class="count bg-info">
        {% transchoice count %}
            {0} There are no records|{1} There is one record|]1,Inf] There are %count% records
        {% endtranschoice %}    
    </div>
    {% if count > 0 %}
        <table class="table table-striped records_list">
            <thead>
                <tr>
                    <th{% if pagination.isSorted('r.name') %} class="sorted"{% endif %}>
                       {{ knp_pagination_sortable(pagination, 'Name'|trans, 'r.name') }}
                    </th>
                    <th{% if pagination.isSorted('rt.name') %} class="sorted"{% endif %}>
                       {{ knp_pagination_sortable(pagination, 'Record Type'|trans, 'rt.name') }}
                    </th>
                    <th>{% trans %}Actions{% endtrans %}</th>
                </tr>
            </thead>
            <tbody>
            {% for entity in pagination %}
                <tr>
                    <td><a href="{{ path('record_show', { 'id': entity.id }) }}">{{ entity.name }}</a></td>
                    <td>{{ entity.recordType.name }}</td>
                    <td>
                    <ul class="list-unstyled">
                        <li>
                            <a href="{{ path('record_show', { 'id': entity.id }) }}">{% trans %}Show{% endtrans %}</a>
                        </li>
                        <li>
                            <a href="{{ path('record_edit', { 'id': entity.id }) }}">{% trans %}Edit{% endtrans %}</a>
                        </li>
                    </ul>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    {% endif %}
<ul class="list-unstyled">
    <li><a href="{{ path('record_wizard') }}" class="btn btn-primary">{% trans %}New{% endtrans %}</a></li>
</ul>
{% endblock %}

src/CrossingBorders/XBundle/Resources/views/Record/new.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'CrossingBordersXBundle:Form:record_fields.html.twig' %}
{% block javascripts %}
    {{ parent() }}
    {% javascripts '@CrossingBordersXBundle/Resources/public/js/record/*' %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        Record.strings.addRow = "{% trans %}Add Row{% endtrans %}";
    </script>
{% endblock %}
{% block body -%}
<h1>{% trans %}New Record{% endtrans %}</h1>
{{ form_start(form) }}
    {% if not form.vars.valid %}
        <p class="text-danger">This record contains errors. Please review them below.</p>
    {% endif %}
    {% for field in form %}
        {% if form.submit == field %}
            {{ form_widget(field, {'attr': {'class': 'btn btn-primary'}}) }}
        {% else %}
            {{form_row(field)}}
        {% endif %}
    {% endfor %}
{{ form_end(form) }}
<ul class="record_actions list-unstyled">
    <li><a href="{{ path('record') }}" class="btn btn-default">Back to the list</a></li>
</ul>
{% endblock %}

src/CrossingBorders/XBundle/Resources/views/Record/show.html.twig
{% extends '::base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets '@FOSCommentBundle/Resources/assets/css/comments.css' %}
    <link rel="stylesheet" href="{{ asset_url }}" type="text/css" />
    {% endstylesheets %}
{% endblock %}

{% block body -%}
    <h1>{% trans %}Record{% endtrans %}</h1>
    <table class="table record_properties">
        <tbody>
            <tr>
                <th>{% trans %}Name{% endtrans %}</th>
                <td>{{ entity.name }}</td>
            </tr>
            {% for field in fieldValues %}
                <tr>
                    <th>{{ field.recordTypeField.name }}</th>
                    <td>
                        {% if field.type == 'Choice' %}
                        <ul class="list-unstyled">
                            {% if field.isMultipleChoice %}
                                {% set inputType = 'checkbox' %}
                            {% else %}
                                {% set inputType = 'radio' %}
                            {% endif %}
                            {% for value in field.value %}
                                <li><input type="{{ inputType }}" checked="checked" disabled="disabled" />{{ value.name }}</li>
                            {% endfor %}
                            {% for value in field.notSelectedChoices %}
                                <li><input type="{{ inputType }}" disabled="disabled" />{{ value.name }}</li>
                            {% endfor %}
                        </ul>
                        {% elseif field.type == 'File' %}
                            <div class="row">
                                <a class="col-xs-12 preview-download-link" href="{{ asset(field.webPathOriginal) }}" download="{{ field.originalName }}">{{ field.originalName }}</a>
                            </div>
                            <div class="row">
                                {% if field.isImage %}
                                    <img   class="col-xs-12 image-preview" src="{{ asset(field.webPath) }}" alt="{{ field.originalName }}" />
                                {% elseif field.isVideo %} 
                                    <video class="col-xs-12 video-preview" src="{{ asset(field.webPathOriginal) }}" controls>
                                        {% trans %}Your browser does not support the <code>video</code> element.{% endtrans %}
                                    </video>
                                {% elseif field.isAudio %} 
                                    <audio class="col-xs-12 audio-preview" src="{{ asset(field.webPathOriginal) }}" controls>
                                        {% trans %}Your browser does not support the <code>audio</code> element.{% endtrans %}
                                    </audio>
                                {% endif %} 
                            </div>
                        {% elseif field.type == 'Records' %}
                            <ul class="list-unstyled">
                                {% for record in field.value %}
                                    <li><a href="{{ path('record_show', { 'id': record.id }) }}">{{ record.name }}</a></li>
                                {% endfor %}
                            </ul>
                        {% elseif field.type == 'Table' %}
                            <table class="table table-condensed nested-table">
                                <thead>
                                    <tr>
                                        {% for column in field.columns %}
                                            <th>{{ column.name }}</th>
                                        {% endfor %}  
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for row in field.rows %}
                                        <tr>
                                            {% for cell in row.cells %}
                                                {% if cell.value is null %}
                                                    <td><a href="{{ path('record_show', { 'id': cell.record.id }) }}">{{ cell.record.name }}</a></td>
                                                {% else %}
                                                    <td>{{ cell.value }}</td>
                                                {% endif %}
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% elseif field.type == 'Boolean' %}
                            {% if field.value %}
                                {% trans %}Yes{% endtrans %}
                            {% else %}
                                {% trans %}No{% endtrans %}
                            {% endif %}  
                        {% elseif field.type == 'Date' %}
                            {{ field.value|date('Y-m-d') }}
                        {% elseif field.type == 'Time' %}
                            {{ field.value|date('H:i:s') }}
                        {% elseif field.type == 'DateTime' %}
                            {{ field.value|date('Y-m-d H:i:s') }}
                        {% elseif field.type == 'Text' %}
                            {{ field.value|raw }}
                        {% else %}
                            {{ field.value }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <th>{% trans %}Created{% endtrans %}</th>
                <td>{{ entity.created|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>{% trans %}Updated{% endtrans %}</th>
                <td>{{ entity.updated|date('Y-m-d H:i:s') }}</td>
            </tr>
        </tbody>
    </table>
    <ul class="record_actions list-unstyled">
        <li><a class="btn btn-primary" href="{{ path('record_edit', { 'id': entity.id }) }}">{% trans %}Edit{% endtrans %}</a></li>
        <li>{{ form_delete(delete_form) }}</li>
        <li><a class="btn btn-default" href="{{ path('record') }}">{% trans %}Back to the list{% endtrans %}</a></li>
    </ul>
    {% include 'FOSCommentBundle:Thread:async.html.twig' with {'id': 'record'~entity.id } %}
{% endblock %}

src/CrossingBorders/XBundle/Resources/views/Record/wizard.html.twig
{% extends '::base.html.twig' %}
{% block body -%}
    <h1>{% trans %}Choose a Record Type{% endtrans %}</h1>
    {{ form(form) }}
    <ul class="list-unstyled record_actions">
        <li><a href="{{ path('record') }}" class="btn btn-default">{% trans %}Back to the list{% endtrans %}</a></li>
    </ul>
{% endblock %}