src/CrossingBorders/XBundle/Entity/StoredFile.php
<?php
namespace CrossingBorders\XBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class StoredFile {
    //Source: http://en.wikipedia.org/wiki/Internet_media_type#Type_image
    public static $imageMimeTypes = array('image/gif',
                                          'image/jpeg',
                                          'image/pjpeg',
                                          'image/png',
                                          'image/tiff',
                                          'image/example');
    public static $videoMimeTypes = array('application/ogg',
                                          'video/avi',
                                          'video/example',
                                          'video/mpeg',
                                          'video/mp4',
                                          'video/ogg',
                                          'video/quicktime',
                                          'video/webm',
                                          'video/x-matroska',
                                          'video/x-ms-wmv',
                                          'video/x-flv');
    public static $audioMimeTypes = array('audio/basic',
                                          'audio/L24',
                                          'audio/mp4',
                                          'audio/mpeg',
                                          'audio/ogg',
                                          'audio/opus',
                                          'audio/vorbis',
                                          'audio/vorbis',
                                          'audio/vnd.rn-realaudio',
                                          'audio/vnd.wave',
                                          'audio/webm',
                                          'audio/example');
    
    protected static $thumbnailSuffix = '.thumbnail.jpeg';
    protected static $thumbnailWidth = 200;
    protected static $thumbnailHeight = 150;
    protected static $thumbnailJpegCompression = 60;
    
    protected static $defaultImageSuffix = '.default.jpeg';
    protected static $defaultImageWidth = 1600;
    protected static $defaultImageHeight = 1200;
    protected static $defaultImageJpegCompression = 80;
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $path;
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $originalName;
    private $file;
    private $temp;
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }
    /**
     * Set value
     *
     * @param File $value
     * @return FieldValueString
     */
    public function setValue($value) {
        $this->setFile($value);
        return $this;
    }
    /**
     * Get value
     *
     * @return File 
     */
    public function getValue() {
        return $this->getFile();
    }
    /**
     * Set path
     *
     * @param string $path
     * @return FieldValueString
     */
    public function setPath($path) {
        $this->path = $path;
        return $this;
    }
    /**
     * Get path
     *
     * @return string 
     */
    public function getPath() {
        //If the path is not set try to return an old path so that a still not deleted file may be used instead!
        if(is_null($this->path)) {
            return $this->temp;
        } else {
            return $this->path;
        }
    }
    /**
     * Set originalName
     *
     * @param string $orignalName
     * @return FieldValueString
     */
    public function setOriginalName($orignalName) {
        $this->originalName = $orignalName;
        return $this;
    }
    /**
     * Get originalName
     *
     * @return string 
     */
    public function getOriginalName() {
        return $this->originalName;
    }
    /**
     * Sets file.
     *
     * @param File $file
     */
    public function setFile($file = null) {
        if($file instanceof File) {
            $this->file = $file;
            // check if we have an old image path
            if (isset($this->path)) {
                // store the old name to delete after the update
                $this->temp = $this->path;
                $this->path = null;
            } else {
                $this->path = 'initial';
            }
        } else if(is_string($file) && $file == 'delete') {
            $this->removeUpload();
        }
        return $this;
    }
    /**
     * Get file.
     *
     * @return File
     */
    public function getFile() {
        if($this->file === null) {
            return new File($this->getAbsolutePath(), true);
        } else {
            return $this->file;
        }
    }
    //Get Multiple Types of Path Methods
    public function getAbsolutePath() {
        return is_null($this->getPath())
            ? null
            : self::getUploadRootDir().'/'.$this->getPath();
    }
    public function getWebPath() {
        return is_null($this->getPath())
            ? null
            : $this->getUploadDir().'/'.$this->getPath().StoredFile::$defaultImageSuffix;
    }
    public function getWebPathOriginal() {
        return is_null($this->getPath())
            ? null
            : $this->getUploadDir().'/'.$this->getPath();
    }
    public function getWebPathThumbnail() {
        return is_null($this->getPath())
            ? null
            : $this->getUploadDir().'/'.$this->getPath().StoredFile::$thumbnailSuffix;
    }
    public static function getUploadRootDir() {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.self::getUploadDir();
    }
    public static function getUploadDir() {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads';
    }
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        $file = $this->getFile();
        if (null !== $file && $file instanceof UploadedFile) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename.'.'.$this->getFile()->guessExtension();
            $this->originalName = $this->getFile()->getClientOriginalName();
        } else {
            $this->path = $this->getFile()->getFilename();
            $this->originalName = $this->getFile()->getFilename();
        }
    }
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (null === $this->getFile()) {
            return;
        }
        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move(self::getUploadRootDir(), $this->path);
        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            if(file_exists(self::getUploadRootDir().'/'.$this->temp)){
                //unlink($this->getUploadRootDir().'/'.$this->temp);
                array_map('unlink', glob(self::getUploadRootDir().'/'.$this->temp.'*'));
            }
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
        $this->generateThumbnail();
        $this->generateDefaultImage();
    }
    /**
     * @ORM\PreRemove()
     */
    public function saveFilenameForRemoval() {
        $this->temp = $this->getAbsolutePath();
    }
    /**
     * @ORM\PostRemove()
     */
    public function removeFile() {
        $file = $this->temp;
        if ($file) {
            array_map('unlink', glob($file.'*'));
        }
    }
    public function getExists() {
        try {
            $filePath = $this->getAbsolutePath();
            new File($filePath);
            return true;
        } catch(FileNotFoundException $e) {
            return false;
        }
    }
    public function getIsImage() {
        try {
            $file = new File($this->getAbsolutePath());
            return in_array($file->getMimeType(), self::$imageMimeTypes);
        } catch(FileNotFoundException $e) {
            return false;
        }
    }
    public function getIsAudio() {
        try {
            $file = new File($this->getAbsolutePath());
            return in_array($file->getMimeType(), self::$audioMimeTypes);
        } catch(FileNotFoundException $e) {
            return false;
        }
    }
    public function getIsVideo() {
        try {
            $file = new File($this->getAbsolutePath());
            return in_array($file->getMimeType(), self::$videoMimeTypes);
        } catch(FileNotFoundException $e) {
            return false;
        }
    }
    private function generateThumbnail() {
        if($this->getIsImage()) {
            $thumbImage = new \Imagick($this->getAbsolutePath());
            //Set compression
            $thumbImage->setImageCompression(\Imagick::COMPRESSION_JPEG);
            $thumbImage->setImageCompressionQuality(StoredFile::$thumbnailJpegCompression);
            //Strip out unneeded meta data
            $thumbImage->stripImage();

src/CrossingBorders/XBundle/Form/CommentType.php
<?php

namespace CrossingBorders\XBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use CrossingBorders\XBundle\Form\DataTransformer\RecordToIdTransformer;

class CommentType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $recordTransformer = new RecordToIdTransformer($options["em"]);
        $builder->add('text','textarea')
                ->add($builder->create('record', 'hidden')->addModelTransformer($recordTransformer));
    }
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CrossingBorders\XBundle\Entity\Comment',
        ));
        $resolver->setRequired(
                                array(
                                        'em'
                                     )
                              );
    }
    /**
     * @return string
     */
    public function getName()
    {
        return 'crossingborders_xbundle_comment';
    }
}

src/CrossingBorders/XBundle/Resources/views/Gallery/advanced.html.twig
{% extends '::base.html.twig' %}
{% block body -%}
<h1>{% trans %}Advanced Gallery{% endtrans %} - <em>{{ recordType.name }}</em></h1>
{{ form_start(form) }}
    {% for field in form %}
        {% if form.submit == field %}
            {{ form_widget(field, {'attr': {'class': 'btn btn-primary'}}) }}
        {% else %}
            {{form_row(field)}}
        {% endif %}
    {% endfor %}
{{ form_end(form) }}
{% endblock %}

src/CrossingBorders/XBundle/Resources/views/Gallery/advancedResults.html.twig
{% extends '::base.html.twig' %}
{% block javascripts %}
    {{ parent() }}
    {% javascripts '@CrossingBordersXBundle/Resources/public/js/gallery/*' %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    {% javascripts '@CrossingBordersXBundle/Resources/public/js/favorite/add.js' %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        Gallery.noMoreResults = '{% trans %}No more results{% endtrans %}';
        Favorites.saveRoute = '{{ path('favorite_add') }}';
        Favorites.savePrompt = '{% trans %}Please enter a unique favorite name{% endtrans %}';
        Favorites.csrfToken = '{{ csrf_token('add-favorite') }}';
    </script>
{% endblock %}
{% block canvas %}
    <div id="canvas-container">
        <div class="gallery-mode-toggle mode-toggle-container">
            <button type="button" class="btn btn-primary mode-toggle-link"><span class="glyphicon glyphicon-chevron-left"></span>{% trans %}Back{% endtrans %}</button>
            <button type="button" class="btn btn-primary save-gallery-screenshot">
                <span class="glyphicon glyphicon-save"></span>
                {% trans %}Save{% endtrans %}
            </button>
        </div>
        <div id="canvas">
        </div>
    </div>
{% endblock %}
{% block menu %}
    {{ parent() }}
    <button type="button" class="btn btn-primary navbar-btn mode-toggle-link navbar-right">
        {% trans %}View Images{% endtrans %}
        <span id="number-of-selected-images" class="badge">0</span>
    </button>
{% endblock %} 
{% macro subFieldsHeader(fields) %}
    {% for key, field in fields %}
        {% if field is iterable %}
            <th>{{ key }}</th>
        {% else %}
            <th>{{ field }}</th>
        {% endif %}
    {% endfor %}
{% endmacro %}
{% macro subFieldsDetail(field, fieldValue) %}
    {% import _self as macros %}
    <a href="{{ path('record_show', { 'id': fieldValue.id }) }}">{{ fieldValue.name }}</a>
    <table class="table table-striped dragtable">
        <thead><tr>{{ macros.subFieldsHeader(field) }}</tr></thead>
        <tbody><tr>{{ macros.subFieldsCell(field, fieldValue) }}</tr></tbody>
    </table>
{% endmacro %}
{% macro subFieldsCell(fields, entity) %}
    {% import _self as macros %}
    {% for key, field in fields %}
        {% if field is iterable %}
            {% set fieldValue = entity.__get(key) %}
            <td>
                {% if fieldValue is iterable %}
                    {% for subFieldValue in fieldValue %}
                        {{ macros.subFieldsDetail(field, subFieldValue) }}
                    {% endfor %}
                {% elseif fieldValue is not null %}
                    {{ macros.subFieldsDetail(field, fieldValue) }}
                {% endif %}
            </td>
        {% else %}
            {% set fieldFile = entity.getFieldValueFile(field) %}
            {% if fieldFile %}
                <td>
                    {% if entity.isFieldValueImage(field) %}
                        <a class="gallery-thumbnail-link"
                           href="javascript:void(0)">
                            <img class="gallery-thumbnail"
                                 alt="{{ fieldFile.originalName }}"
                                 src="{{ asset(fieldFile.webPathThumbnail) }}"
                                 data-image-url="{{ asset(fieldFile.webPath) }}" />
                        </a>
                    {% else %}
                        <a href="{{ asset(fieldFile.webPath) }}">
                            {{ fieldFile.originalName }}
                        </a>
                    {% endif %}
                </td>
            {% else %}
                {% set fieldValue = entity.__get(field) %}
                <td>{{ fieldValue }}</td>
            {% endif %}
        {% endif %}
    {% endfor %}
{% endmacro %}
{% block body -%}
    {% import _self as macros %}
    <h1>{% trans %}Records{% endtrans %}
        {% if app.user %}
            <button type="button" class="save-search btn btn-primary">
                <span class="glyphicon glyphicon-star"></span>
            </button>
        {% endif %}
        <button type="button" class="print-page btn btn-primary">
            <span class="glyphicon glyphicon-print"></span>
        </button>
        <button type="button" class="export-page-to-pdf btn btn-primary">
            <span class="fa fa-file-pdf-o"></span>
        </button>
    </h1>
    <div class="count bg-info">
        {% transchoice count %}
            {0} There are no records|{1} There is one record|]1,Inf] There are %count% records
        {% endtranschoice %}    
    </div>
{% if count > 0 %}
    <table class="table table-striped records_list dragtable gallery-table">
        <thead>
            <tr>
                <th>
                   {{ 'Name'|trans }}
                </th>
                <th>
                   {{'Record Type'|trans }}
                </th>
                   {{ macros.subFieldsHeader(shownFields) }}
                <th>{% trans %}Actions{% endtrans %}</th>
            </tr>
        </thead>
        <tbody class="gallery-results-table-body"></tbody>
    </table>
    <div class="navigation">
        <button type="button" class="btn btn-primary gallery-load-more has-spinner">
            {% trans %}More results{% endtrans %} <span class="spinner"><i class="fa fa-spinner fa-spin"></i></span>
        </button>
    </div>
{% endif %}
<ul class="list-unstyled">
    <li><a href="{{ path('record_wizard') }}" class="btn btn-primary">{% trans %}New{% endtrans %}</a></li>
</ul>
{% endblock %}

src/CrossingBorders/XBundle/Resources/views/Gallery/advancedResultsPage.html.twig
{% macro subFieldsHeader(fields) %}
    {% for key, field in fields %}
        {% if field is iterable %}
            <th>{{ key }}</th>
        {% else %}
            <th>{{ field }}</th>
        {% endif %}
    {% endfor %}
{% endmacro %}
{% macro subFieldsDetail(field, fieldValue) %}
    {% import _self as macros %}
    <a href="{{ path('record_show', { 'id': fieldValue.id }) }}">{{ fieldValue.name }}</a>
    <table class="table table-striped dragtable">
        <thead><tr>{{ macros.subFieldsHeader(field) }}</tr></thead>
        <tbody><tr>{{ macros.subFieldsCell(field, fieldValue) }}</tr></tbody>
    </table>
{% endmacro %}
{% macro subFieldsCell(fields, entity) %}
    {% import _self as macros %}
    {% for key, field in fields %}
        {% if field is iterable %}
            {% set fieldValue = entity.__get(key) %}
            <td>
                {% if fieldValue is iterable %}
                    {% for subFieldValue in fieldValue %}
                        {{ macros.subFieldsDetail(field, subFieldValue) }}
                    {% endfor %}
                {% elseif fieldValue is not null %}
                    {{ macros.subFieldsDetail(field, fieldValue) }}
                {% endif %}
            </td>
        {% else %}
            {% set fieldFile = entity.getFieldValueFile(field) %}
            {% if fieldFile %}
                <td>
                    {% if entity.isFieldValueImage(field) %}
                        <a class="gallery-thumbnail-link" href="javascript:void(0)">
                            <img class="gallery-thumbnail"
                                 alt="{{ fieldFile.originalName }}"
                                 src="{{ asset(fieldFile.webPathThumbnail) }}"
                                 data-image-url="{{ asset(fieldFile.webPath) }}" />
                        </a>
                    {% else %}
                        <a href="{{ asset(fieldFile.webPath) }}">
                            {{ fieldFile.originalName }}
                        </a>
                    {% endif %}
                </td>
            {% else %}
                {% set fieldValue = entity.getValueAndType(field) %}
                {% if fieldValue['value'] is iterable %}
                    <td>
                        {% if fieldValue['type'] == 'Table' %}
                            <table class="table table-striped">
                                {% for row in fieldValue['value'] %}
                                    <tr>
                                        {% for cell in row %}
                                            <td>{{ cell }}</td>
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            </table>
                        {% else %}
                            <ul>
                                {% for value in fieldValue['value'] %}
                                    <li>{{ value }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </td>
                {% else %}
                    {% if fieldValue['type'] == 'Date' %}
                        <td>{{ fieldValue['value']|date('Y-m-d') }}</td>
                    {% elseif fieldValue['type'] == 'Time' %}
                        <td>{{ fieldValue['value']|date('H:i:s') }}</td>
                    {% elseif fieldValue['type'] == 'Date Time' %}
                        <td>{{ fieldValue['value']|date('Y-m-d H:i:s') }}</td>
                    {% else %}
                        <td>{{ fieldValue['value'] }}</td>
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endif %}
    {% endfor %}
{% endmacro %}
{% import _self as macros %}
{% for entity in pagination %}
    <tr>
        <td><a href="{{ path('record_show', { 'id': entity.id }) }}">{{ entity.name }}</a></td>
        <td>{{ entity.recordType.name }}</td>
        {{ macros.subFieldsCell(shownFields, entity) }}
        <td>
            <ul class="list-unstyled">
                <li>
                    <a href="{{ path('record_show', { 'id': entity.id }) }}">{% trans %}Show{% endtrans %}</a>
                </li>
                <li>
                    <a href="{{ path('record_edit', { 'id': entity.id }) }}">{% trans %}Edit{% endtrans %}</a>
                </li>
            </ul>
        </td>
    </tr>
{% endfor %}

src/CrossingBorders/XBundle/Resources/views/Gallery/advancedWizard.html.twig
{% extends '::base.html.twig' %}
{% block body -%}
<h1>{% trans %}Gallery{% endtrans %}</h1>
<h3>{% trans %}Choose a record type{% endtrans %}</h3>
{{ form(form) }}
{% endblock %}

src/CrossingBorders/XBundle/Resources/views/Gallery/simple.html.twig
{% extends '::base.html.twig' %}
{% block body -%}
<h1>{% trans %}Simple Gallery Search{% endtrans %}</h1>
{{ form_start(form) }}
    {% for field in form %}
        {% if form.submit == field %}
            {{ form_widget(field, {'attr': {'class': 'btn btn-primary'}}) }}
        {% else %}
            {{form_row(field)}}
        {% endif %}
    {% endfor %}
{{ form_end(form) }}
{% endblock %}

src/CrossingBorders/XBundle/Resources/views/Gallery/simpleResults.html.twig
{% extends '::base.html.twig' %}
{% block javascripts %}
    {{ parent() }}
    {% javascripts '@CrossingBordersXBundle/Resources/public/js/gallery/*' %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    {% javascripts '@CrossingBordersXBundle/Resources/public/js/favorite/add.js' %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        Gallery.noMoreResults = '{% trans %}No more results{% endtrans %}';
        Favorites.saveRoute = '{{ path('favorite_add') }}';
        Favorites.savePrompt = '{% trans %}Please enter a unique favorite name{% endtrans %}';
        Favorites.csrfToken = '{{ csrf_token('add-favorite') }}';
    </script>
{% endblock %}
{% block canvas %}
    <div id="canvas-container">
        <div class="gallery-mode-toggle mode-toggle-container">
            <button type="button" class="btn btn-primary mode-toggle-link"><span class="glyphicon glyphicon-chevron-left"></span>{% trans %}Back{% endtrans %}</button>
            <button type="button" class="btn btn-primary save-gallery-screenshot">
                <span class="glyphicon glyphicon-save"></span>
                {% trans %}Save{% endtrans %}
            </button>
        </div>
        <div id="canvas">
        </div>
    </div>
{% endblock %}
{% block menu %}
    {{ parent() }}
    <button type="button" class="btn btn-primary navbar-btn mode-toggle-link navbar-right">
        {% trans %}View Images{% endtrans %}
        <span id="number-of-selected-images" class="badge">0</span>
    </button>
{% endblock %} 
{% block body -%}
    <h1>{% trans %}Gallery{% endtrans %}
        {% if app.user %}
            <button type="button" class="save-search btn btn-primary">
                <span class="glyphicon glyphicon-star"></span>
            </button>
        {% endif %}
        <button type="button" class="print-page btn btn-primary">
            <span class="glyphicon glyphicon-print"></span>
        </button>
        <button type="button" class="export-page-to-pdf btn btn-primary">
            <span class="fa fa-file-pdf-o"></span>
        </button>
    </h1>
    <div class="count bg-info">
        {% transchoice count %}
            {0} There are no records|{1} There is one record|]1,Inf] There are %count% records
        {% endtranschoice %}    
    </div>
{% if count > 0 %}
    <table id='records-table' class="table table-striped records_list dragtable gallery-table">
        <thead>
            <tr>
                <th{% if pagination.isSorted('r.name') %} class="sorted"{% endif %}>
                   {{ knp_pagination_sortable(pagination, 'Name'|trans, 'r.name') }}
                </th>
                <th{% if pagination.isSorted('rt.name') %} class="sorted"{% endif %}>
                   {{ knp_pagination_sortable(pagination, 'Record Type'|trans, 'rt.name') }}
                </th>
                <th class="galery-values-header">{% trans %}Images{% endtrans %}</th>
                <th>{% trans %}Actions{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in pagination %}
            <tr>
                <td><a href="{{ path('record_show', { 'id': entity.id }) }}">{{ entity.name }}</a></td>
                <td>{{ entity.recordType.name }}</td>
                <td><div class="row sortable">
                        {% for fieldValue in entity.fieldValues %}
                            {% if fieldValue.recordTypeField.fieldType.name == 'Image' %}
                                <div class="col-md-4">
                                    <div>{{ fieldValue.recordTypeField.name }}</div>
                                    <div>
                                        <a class="gallery-thumbnail-link" href="javascript:void(0)">
                                            <img class="gallery-thumbnail"
                                                 alt="{{ fieldValue.storedFile.originalName }}"
                                                 src="{{ asset(fieldValue.webPathThumbnail) }}"
                                                 data-image-url="{{ asset(fieldValue.webPath) }}" />
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </td>
                <td>
                    <ul class="list-unstyled">
                        <li>
                            <a href="{{ path('record_show', { 'id': entity.id }) }}">{% trans %}Show{% endtrans %}</a>
                        </li>
                        <li>
                            <a href="{{ path('record_edit', { 'id': entity.id }) }}">{% trans %}Edit{% endtrans %}</a>
                        </li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endif %}
    <ul class="list-unstyled">
        <li><a href="{{ path('record_wizard') }}" class="btn btn-primary">{% trans %}New{% endtrans %}</a></li>
    </ul>
{% endblock %}